#!/usr/bin/python3
from datetime import datetime as d
from subprocess import run
from sys import argv
if d.now().weekday() < 7 and len(argv) > 1 and run([argv[1]]).returncode == -4:
    print('252'*252252)
    exit(-4)
