# version: '42'  # Specify the Docker Compose version
name: "kodmaschine"

services:
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./rendu:/rendu
      - ./result:/result
      - ./scoreboard:/scoreboard
    restart: 'unless-stopped'

  moulinette:
    build:
      context: ./moulinette
      dockerfile: Dockerfile
    volumes:
      - ./rendu:/rendu
      - ./result:/result
    restart: 'unless-stopped'
