# version: '42'  # Specify the Docker Compose version
name: "kodmaschine"

services:
  user:
    build:
      context: ./user  # Path to the user Dockerfile
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./rendu:/rendu  # Mount the rendu directory for shared access
    restart: 'no'

  moulinette:
    build:
      context: ./moulinette  # Path to the moulinette Dockerfile
      dockerfile: Dockerfile
    volumes:
      - ./rendu:/rendu  # Mount the rendu directory for shared access
    restart: 'no' 
    # profiles:
    #   - brb
    # TODO - run only moulinete on BIG RED BUTTON (BRB)
    #
