#!/bin/sh
echo RUNNING SCOREBOARD SCRIPT

### SCOREBOARD ###
cat /scoreboard/score.board > /scoreboard/score.board.bak

# Create a scoreboard file if it doesn't exist
if [ ! -f /scoreboard/score.board ]; then
    touch /scoreboard/score.board
fi

CLVL=3
FAIL=1

grep -Fqx "[N/A]" /result/3
if [ $? -eq 0 ]; then
    CLVL=2
fi

grep -Fqx "[N/A]" /result/2
if [ $? -eq 0 ]; then
    CLVL=1
fi

grep -Fqx "[OK]" /result/$CLVL
if [ $? -eq 0 ]; then
    CLVL=$((CLVL+1))
    FAIL=0
fi

subjectpdf="clear; cat en.subject$CLVL.pdf | /tte print"
challenge="sleep 0.1; vim challenge$CLVL.c +16"
# Prompt user from tmux to enter their name
if [ $FAIL -eq 0 ]; then
    echo "[WIP]" > /result/$CLVL
    tmux popup -E -t kodmaschine "cat /result/$((CLVL - 1)) | figlet -t -c | /tte beams ; sleep 2"
    tmux popup -E -t kodmaschine 'figlet "Level '"$((CLVL - 1))"' passed!" && echo "username: " && read name && echo "$name" > /scoreboard/new_entry && sleep .5'
    tmux select-pane -t 2
    tmux send-keys -t kodmaschine "$subjectpdf" C-m
    tmux select-pane -t 3
    killall -9 vim 2>/dev/null
    tmux send-keys -t kodmaschine "$challenge" C-m
else
    tmux popup -E -t kodmaschine "cat /result/$((CLVL)) | figlet -t -c | /tte beams ; sleep 2"
    echo "Exiting because of exam fail"
    exit
fi

# Wait for user to enter their name
while [ ! -s /scoreboard/new_entry ]; do
    sleep 0.5
done

# Read the user's name
name=$(cat /scoreboard/new_entry)

# Get current user time
time=$(cat /scoreboard/current_user_time)

# Add user to scoreboard
echo "$((CLVL-1)) $time $name" >> /scoreboard/score.board

# Sort scoreboard
sort -k1,1nr -k2,2n -k3,3n /scoreboard/score.board > /scoreboard/score.board.sorted
mv /scoreboard/score.board.sorted /scoreboard/score.board

# End if challenge complete
if [ $CLVL -eq 4 ]; then
	sleep 0.1
	tmux popup -E -t kodmaschine "figlet -t -c Congrats $name | /tte fireworks --launch-delay 2 ; echo 'Exam passed! Rebooting...'"
	sleep 42
	tmux kill-session -t kodmaschine
	# tmux kill-server # maybe use this
fi
